"""Register metadata for heat pumps (hmu/hmux0/vwz*), boilers (bai) and their fallbacks."""

from __future__ import annotations

from .models import RegisterMeta

HEAT_PUMP_AND_BOILER_REGISTERS: dict[str, RegisterMeta] = {
    # hmu (Heat Pump)
    "hmu.Status01": RegisterMeta(
        friendly_name="Status",
        icon="mdi:information",
        entity_category="diagnostic",
    ),
    "hmu.Status00": RegisterMeta(
        friendly_name="Compressor Status",
        icon="mdi:information",
        entity_category="diagnostic",
    ),
    "hmu.Status00.supplytemp": RegisterMeta(
        friendly_name="Status Flow Temperature", device_class="temperature", unit="°C"
    ),
    "hmu.Status00.waterpressure": RegisterMeta(
        friendly_name="Status Water Pressure", device_class="pressure", unit="bar"
    ),
    "hmu.Status00.compressormodulation": RegisterMeta(friendly_name="Status Compressor Modulation", unit="%"),
    "hmu.Status00.compressorstate": RegisterMeta(friendly_name="Status Compressor State"),
    "hmu.Status00.heatingstate": RegisterMeta(friendly_name="Status Heating State"),
    "hmu.Status00.defrost": RegisterMeta(friendly_name="Defrost Active", entity_type="binary_sensor"),
    "hmu.Status00.compressorpower": RegisterMeta(friendly_name="Status Compressor Power", unit="%"),
    "hmu.RunDataElPowerConsumption": RegisterMeta(
        friendly_name="Electrical Power Consumption", device_class="power", unit="W"
    ),
    "hmu.Status01.temp": RegisterMeta(
        friendly_name="Flow Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "hmu.Status01.temp_1": RegisterMeta(
        friendly_name="Return Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "hmu.Status01.temp_2": RegisterMeta(
        friendly_name="Outside Temperature",
        device_class="temperature",
        unit="°C",
        enabled=False,
    ),
    "hmu.Status01.temp_3": RegisterMeta(
        friendly_name="Hot Water Temperature",
        device_class="temperature",
        unit="°C",
        enabled=False,
    ),
    "hmu.Status01.temp_4": RegisterMeta(
        friendly_name="Storage Temperature",
        device_class="temperature",
        unit="°C",
        enabled=False,
    ),
    "hmu.Status01.pumpstate": RegisterMeta(
        friendly_name="Pump State",
        entity_type="binary_sensor",
        entity_category="diagnostic",
    ),
    "hmux0.Status01": RegisterMeta(
        friendly_name="Status",
        icon="mdi:information",
        entity_category="diagnostic",
    ),
    "hmux0.Status01.temp": RegisterMeta(
        friendly_name="Flow Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "hmux0.Status01.temp_1": RegisterMeta(
        friendly_name="Return Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "hmux0.Status01.temp_2": RegisterMeta(
        friendly_name="Outside Temperature",
        device_class="temperature",
        unit="°C",
        enabled=False,
    ),
    "hmux0.Status01.temp_3": RegisterMeta(
        friendly_name="Hot Water Temperature",
        device_class="temperature",
        unit="°C",
        enabled=False,
    ),
    "hmux0.Status01.temp_4": RegisterMeta(
        friendly_name="Storage Temperature",
        device_class="temperature",
        unit="°C",
        enabled=False,
    ),
    "hmux0.Status01.pumpstate": RegisterMeta(
        friendly_name="Pump State",
        entity_type="binary_sensor",
        entity_category="diagnostic",
    ),
    "hmu.StatusCirPump": RegisterMeta(
        friendly_name="Circulation Pump",
        entity_type="binary_sensor",
        entity_category="diagnostic",
    ),
    "hmu.Currenterror": RegisterMeta(
        friendly_name="Error",
        icon="mdi:alert",
        entity_category="diagnostic",
    ),
    "hmu.FlowTemp": RegisterMeta(
        friendly_name="Flow Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "hmu.FlowTemperature": RegisterMeta(
        friendly_name="Flow Temperature (alt)",
        device_class="temperature",
        unit="°C",
    ),
    "hmu.RunDataCompressorSpeed": RegisterMeta(
        friendly_name="Compressor Speed",
        icon="mdi:speedometer",
        unit="rps",
    ),
    "hmu.RunDataHighPressure": RegisterMeta(
        friendly_name="High Pressure",
        device_class="pressure",
        unit="bar",
    ),
    "hmu.RunDataLowPressure": RegisterMeta(
        friendly_name="Low Pressure",
        device_class="pressure",
        unit="bar",
        enabled=False,
    ),
    "hmu.RunDataCompressorInletTemp": RegisterMeta(
        friendly_name="Compressor Inlet Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "hmu.RunDataCompressorOutletTemp": RegisterMeta(
        friendly_name="Compressor Outlet Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "hmu.RunDataEEVOutletTemp": RegisterMeta(
        friendly_name="EEV Outlet Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "hmu.RunDataEEVPositionAbs": RegisterMeta(
        friendly_name="EEV Position",
        icon="mdi:valve",
        unit="%",
    ),
    "hmu.RunDataFan1Speed": RegisterMeta(
        friendly_name="Fan 1 Speed",
        icon="mdi:fan",
        unit="rpm",
    ),
    "hmu.RunDataFan2Speed": RegisterMeta(
        friendly_name="Fan 2 Speed",
        icon="mdi:fan",
        unit="rpm",
    ),
    "hmu.RunDataStatuscode": RegisterMeta(
        friendly_name="Compressor Status",
        icon="mdi:information",
    ),
    "hmu.RunDataAirInletTemp": RegisterMeta(
        friendly_name="Air Inlet Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "hmux0.RunDataFlowTemp": RegisterMeta(
        friendly_name="Flow Temperature (precise)",
        device_class="temperature",
        unit="°C",
    ),
    "hmu.RunDataReturnTemp": RegisterMeta(
        friendly_name="Return Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "hmu.RunDataBuildingCPumpPower": RegisterMeta(
        friendly_name="Building Circulation Pump Speed",
        unit="%",
    ),
    "hmux0.KmKreisVerflTemp": RegisterMeta(
        friendly_name="Refrigerant Condensing Temperature",
        device_class="temperature",
        unit="°C",
        entity_category="diagnostic",
        fallback_read=False,
    ),
    "hmux0.UnterkuehlungSoll": RegisterMeta(
        friendly_name="Subcooling Target",
        device_class="temperature",
        unit="K",
        entity_category="diagnostic",
        fallback_read=False,
    ),
    "hmux0.UnterkuehlungIst": RegisterMeta(
        friendly_name="Subcooling Actual",
        device_class="temperature",
        unit="K",
        entity_category="diagnostic",
        fallback_read=False,
    ),
    "hmux0.EEVAuslassTemp": RegisterMeta(
        friendly_name="EEV Outlet Temperature",
        device_class="temperature",
        unit="°C",
        entity_category="diagnostic",
        fallback_read=False,
    ),
    "hmux0.KmKreisKompEinlTemp": RegisterMeta(
        friendly_name="Compressor Inlet Temperature",
        device_class="temperature",
        unit="°C",
        entity_category="diagnostic",
        fallback_read=False,
    ),
    "hmux0.KmKreisKompAuslTemp": RegisterMeta(
        friendly_name="Compressor Outlet Temperature",
        device_class="temperature",
        unit="°C",
        entity_category="diagnostic",
        fallback_read=False,
    ),
    "hmux0.KmKreisHochdruck": RegisterMeta(
        friendly_name="Refrigerant High Pressure",
        device_class="pressure",
        unit="bar",
        entity_category="diagnostic",
        fallback_read=False,
    ),
    "hmu.BuildingCircuitPumpSpeed": RegisterMeta(
        friendly_name="Building Circuit Pump Speed",
        unit="%",
    ),
    "hmu.CurrentConsumedPower": RegisterMeta(
        friendly_name="Compressor Power",
        device_class="power",
        unit="kW",
    ),
    "hmu.CurrentYieldPower": RegisterMeta(
        friendly_name="Thermal Output",
        device_class="power",
        unit="kW",
    ),
    "hmu.CurrentCompressorUtil": RegisterMeta(
        friendly_name="Compressor Utilisation",
        icon="mdi:percent",
        unit="%",
    ),
    "hmu.SupplyTempWeighted": RegisterMeta(
        friendly_name="Supply Temperature (weighted)",
        device_class="temperature",
        unit="°C",
    ),
    "hmu.SourceTempInput": RegisterMeta(
        friendly_name="Source Temp Input",
        device_class="temperature",
        unit="°C",
    ),
    "hmu.SourceTempOutput": RegisterMeta(
        friendly_name="Source Temp Output",
        device_class="temperature",
        unit="°C",
    ),
    "hmu.TotalEnergyUsage": RegisterMeta(
        friendly_name="Total Energy",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "hmu.CopHc": RegisterMeta(
        friendly_name="COP Heating",
        icon="mdi:lightning-bolt",
        state_class="measurement",
    ),
    "hmu.CopHcMonth": RegisterMeta(
        friendly_name="COP Heating Month",
        icon="mdi:lightning-bolt",
        state_class="measurement",
    ),
    "hmu.CopHwc": RegisterMeta(
        friendly_name="COP DHW",
        icon="mdi:lightning-bolt",
        state_class="measurement",
    ),
    "hmu.CopHwcMonth": RegisterMeta(
        friendly_name="COP DHW Month",
        icon="mdi:lightning-bolt",
        state_class="measurement",
    ),
    "hmu.CopCooling": RegisterMeta(
        friendly_name="COP Cooling",
        icon="mdi:lightning-bolt",
        state_class="measurement",
    ),
    "hmu.CopCoolingMonth": RegisterMeta(
        friendly_name="COP Cooling Month",
        icon="mdi:lightning-bolt",
        state_class="measurement",
    ),
    "hmu.YieldHc": RegisterMeta(
        friendly_name="Yield Heating",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "hmu.YieldHcDay": RegisterMeta(
        friendly_name="Yield Heating Today",
        device_class="energy",
        unit="kWh",
    ),
    "hmu.YieldHcMonth": RegisterMeta(
        friendly_name="Yield Heating Month",
        device_class="energy",
        unit="kWh",
    ),
    "hmu.YieldHwc": RegisterMeta(
        friendly_name="Yield DHW",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "hmu.YieldHwcDay": RegisterMeta(
        friendly_name="Yield DHW Today",
        device_class="energy",
        unit="kWh",
    ),
    "hmu.YieldHwcMonth": RegisterMeta(
        friendly_name="Yield DHW Month",
        device_class="energy",
        unit="kWh",
    ),
    "hmu.YieldCoolDay": RegisterMeta(
        friendly_name="Yield Cooling Today",
        device_class="energy",
        unit="kWh",
    ),
    # eloBLOCK VE 28 / BAI00 community capture (issue #103).
    "bai.FlowTemp": RegisterMeta(
        friendly_name="Flow Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "bai.FlowTempDesired": RegisterMeta(
        friendly_name="Flow Temperature Desired",
        device_class="temperature",
        unit="°C",
    ),
    "bai.StorageTemp": RegisterMeta(
        friendly_name="Storage Temperature",
        device_class="temperature",
        unit="°C",
    ),
    "bai.StorageTempDesired": RegisterMeta(
        friendly_name="Storage Temperature Desired",
        device_class="temperature",
        unit="°C",
    ),
    "bai.WaterPressure": RegisterMeta(
        friendly_name="Water Pressure",
        device_class="pressure",
        unit="bar",
    ),
    "bai.HeatingStage1": RegisterMeta(
        friendly_name="Heating Element Stage 1",
        entity_type="binary_sensor",
    ),
    "bai.HeatingStage3": RegisterMeta(
        friendly_name="Heating Element Stage 3",
        entity_type="binary_sensor",
    ),
    "bai.ActiveStages": RegisterMeta(
        friendly_name="Active Heating Stages",
        entity_category="diagnostic",
    ),
    # Raw uint32 accumulators of unproven unit (issue #152): the F34 value grew by 90032 in 12 minutes, which no
    # boiler delivers in kWh, and upstream issue #387 shows the counter at 2^32-80. No unit, energy class or
    # statistics class is claimed until a unit is evidenced; the entities are disabled by default.
    "bai.PrEnergySumHc1": RegisterMeta(
        friendly_name="Heating Energy Stage 1 (raw counter)",
        icon="mdi:counter",
        state_class="total_increasing",
        entity_category="diagnostic",
        enabled=False,
    ),
    "bai.PrEnergySumHwc1": RegisterMeta(
        friendly_name="Hot Water Energy Stage 1 (raw counter)",
        icon="mdi:counter",
        state_class="total_increasing",
        entity_category="diagnostic",
        enabled=False,
    ),
    # ecoTEC Plus VMW 30 CS/1-5 / additional BAI endpoints.
    "bai.HwcWaterflow": RegisterMeta(
        friendly_name="Hot Water Flow",
        unit="L/min",
        device_class="volume_flow_rate",
        state_class="measurement",
    ),
    "bai.PrimaryCircuitFlowrate": RegisterMeta(
        friendly_name="Primary Circuit Flow Rate",
        unit="L/min",
        device_class="volume_flow_rate",
        state_class="measurement",
    ),
    "bai.StatFuelSum": RegisterMeta(
        friendly_name="Fuel Energy",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "bai.StatFuelSumHc": RegisterMeta(
        friendly_name="Fuel Energy (Heating)",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "bai.StatFuelSumHwc": RegisterMeta(
        friendly_name="Fuel Energy (DHW)",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    # eloBLOCK/BAI boiler on/off control (issue #111). Exposed as switches; the
    # integration redefines them writable on B509 for BAI hardware.
    "bai.HeatingSwitch": RegisterMeta(
        friendly_name="Heating Switch",
        entity_type="switch",
        writable=True,
        icon="mdi:radiator",
    ),
    "bai.HwcSwitch": RegisterMeta(
        friendly_name="DHW Switch",
        entity_type="switch",
        writable=True,
        icon="mdi:water-boiler",
    ),
    # HMUX0 SW0407/HW0504 environmental-yield counters (issue #161).
    "hmu.HcEnvYieldTotal": RegisterMeta(
        friendly_name="Heating Environmental Energy Total",
        device_class="energy",
        unit="Wh",
        state_class="total_increasing",
        fallback_read=False,
        icon="mdi:radiator",
    ),
    "hmu.HcEnvYieldDay": RegisterMeta(
        friendly_name="Heating Environmental Energy Today",
        device_class="energy",
        unit="Wh",
        state_class="total_increasing",
        fallback_read=False,
        icon="mdi:radiator",
    ),
    "hmu.HcEnvYieldMonth": RegisterMeta(
        friendly_name="Heating Environmental Energy Month",
        device_class="energy",
        unit="Wh",
        state_class="total_increasing",
        fallback_read=False,
        icon="mdi:radiator",
    ),
    "hmu.HwcEnvYieldTotal": RegisterMeta(
        friendly_name="DHW Environmental Energy Total",
        device_class="energy",
        unit="Wh",
        state_class="total_increasing",
        fallback_read=False,
        icon="mdi:water-boiler",
    ),
    "hmu.HwcEnvYieldDay": RegisterMeta(
        friendly_name="DHW Environmental Energy Today",
        device_class="energy",
        unit="Wh",
        state_class="total_increasing",
        fallback_read=False,
        icon="mdi:water-boiler",
    ),
    "hmu.HwcEnvYieldMonth": RegisterMeta(
        friendly_name="DHW Environmental Energy Month",
        device_class="energy",
        unit="Wh",
        state_class="total_increasing",
        fallback_read=False,
        icon="mdi:water-boiler",
    ),
    # Runtime-defined b516 cooling-energy registers (issue #50). The bus
    # reports Wh; the unit stays Wh because ebusd returns the raw EXP value.
    "hmu.CoolEnvYieldTotal": RegisterMeta(
        friendly_name="Cooling Energy Total",
        device_class="energy",
        unit="Wh",
        state_class="total_increasing",
        icon="mdi:snowflake",
    ),
    "hmu.CoolEnvYieldDay": RegisterMeta(
        friendly_name="Cooling Energy Today",
        device_class="energy",
        unit="Wh",
        icon="mdi:snowflake",
    ),
    "hmu.CoolEnvYieldMonth": RegisterMeta(
        friendly_name="Cooling Energy Month",
        device_class="energy",
        unit="Wh",
        icon="mdi:snowflake",
    ),
    "hmu.CoolElecConsTotal": RegisterMeta(
        friendly_name="Cooling Electricity Total",
        device_class="energy",
        unit="Wh",
        state_class="total_increasing",
        icon="mdi:snowflake",
    ),
    "hmu.CoolElecConsDay": RegisterMeta(
        friendly_name="Cooling Electricity Today",
        device_class="energy",
        unit="Wh",
        icon="mdi:snowflake",
    ),
    "hmu.HcElecConsTotal": RegisterMeta(
        friendly_name="Heating Electricity Total",
        device_class="energy",
        unit="Wh",
        state_class="total_increasing",
        icon="mdi:radiator",
    ),
    "hmu.HcElecConsDay": RegisterMeta(
        friendly_name="Heating Electricity Today",
        device_class="energy",
        unit="Wh",
        state_class="total_increasing",
        icon="mdi:radiator",
    ),
    "hmu.HwcElecConsTotal": RegisterMeta(
        friendly_name="DHW Electricity Total",
        device_class="energy",
        unit="Wh",
        state_class="total_increasing",
        icon="mdi:water-boiler",
    ),
    "hmu.HwcElecConsDay": RegisterMeta(
        friendly_name="DHW Electricity Today",
        device_class="energy",
        unit="Wh",
        state_class="total_increasing",
        icon="mdi:water-boiler",
    ),
    "ctlv3.YieldTotal": RegisterMeta(
        friendly_name="Yield Total",
        device_class="energy",
        unit="kWh",
        state_class="total",
        icon="mdi:counter",
        fallback_read=False,
    ),
    "vwzio.PowerConsumptionVwz": RegisterMeta(
        friendly_name="Hydraulic Station Power Consumption",
        device_class="power",
        unit="kW",
        icon="mdi:flash",
        fallback_read=False,
    ),
    # Strong assumption (issue #161): B516 source 0x49 / usage 04 on the VWZIO is the DHW heat delivered by the
    # backup heater in Wh. Upstream names no register for source 9, so the entity stays disabled by default.
    "vwzio.HeaterYieldHwcTotal": RegisterMeta(
        friendly_name="Backup Heater DHW Heat Total",
        device_class="energy",
        unit="Wh",
        state_class="total_increasing",
        icon="mdi:water-boiler",
        enabled=False,
        fallback_read=False,
    ),
    "vwzio.RunStatsImmersionHeaterHwc": RegisterMeta(
        friendly_name="Backup Heater DHW Stats",
        icon="mdi:information",
        entity_category="diagnostic",
        enabled=False,
        fallback_read=False,
    ),
    "vwzio.RunStatsImmersionHeaterHwc.runtime": RegisterMeta(
        friendly_name="Backup Heater Runtime (DHW)",
        device_class="duration",
        unit="min",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
        fallback_read=False,
    ),
    "vwzio.RunStatsImmersionHeaterHwc.cycles": RegisterMeta(
        friendly_name="Backup Heater Starts (DHW)",
        icon="mdi:counter",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
        fallback_read=False,
    ),
    # CSV/find-based electric registers that supplement the runtime-defined
    # b516 counters above (issue #50). Units follow the upstream 08.hmu.tsp
    # definitions: energy is UIN kWh, RunDataElectricPowerConsumption is EXP W,
    # LiveMonitorCurrentConsumedPower is UIN kW with a divisor of 10, and the
    # StatSolar* sums are EXP kWh. All are opt-in: entities only appear when
    # the discovery graph carries them with data.
    "hmu.ConsumptionTotal": RegisterMeta(
        friendly_name="Electrical Energy Consumption",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "hmu.RunDataElectricPowerConsumption": RegisterMeta(
        friendly_name="Electric Power Consumption",
        device_class="power",
        unit="W",
    ),
    "hmu.LiveMonitorCurrentConsumedPower": RegisterMeta(
        friendly_name="Live Power Consumption",
        device_class="power",
        unit="kW",
    ),
    "hmu.StatSolarEnergySum": RegisterMeta(
        friendly_name="Solar Energy Sum",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "hmu.StatSolarEnergySumHc": RegisterMeta(
        friendly_name="Solar Energy Sum (Heating)",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "hmu.StatSolarEnergySumHwc": RegisterMeta(
        friendly_name="Solar Energy Sum (DHW)",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "hmu.YieldCooling": RegisterMeta(
        friendly_name="Yield Cooling",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "hmu.YieldCoolingMonth": RegisterMeta(
        friendly_name="Yield Cooling Month",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "hmu.HoursCool": RegisterMeta(
        friendly_name="Cooling Runtime",
        device_class="duration",
        unit="h",
        state_class="total_increasing",
        entity_category="diagnostic",
    ),
    "hmu.StatElectricEnergySumCool": RegisterMeta(
        friendly_name="Electric Energy Cooling",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "hmu.StatEnvironmentEnergySumCool": RegisterMeta(
        friendly_name="Environment Energy Cooling",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "hmu.StatElectricEnergySum": RegisterMeta(
        friendly_name="Electric Energy",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "hmu.StatElectricEnergySumHc": RegisterMeta(
        friendly_name="Electric Energy (Heating)",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "hmu.StatElectricEnergySumHwc": RegisterMeta(
        friendly_name="Electric Energy (DHW)",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "hmu.StatEnvironmentEnergySum": RegisterMeta(
        friendly_name="Environment Energy",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "hmu.StatEnvironmentEnergySumHc": RegisterMeta(
        friendly_name="Environment Energy (Heating)",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "hmu.StatEnvironmentEnergySumHwc": RegisterMeta(
        friendly_name="Environment Energy (DHW)",
        device_class="energy",
        unit="kWh",
        state_class="total_increasing",
    ),
    "hmu.RunStatsCompressorHours": RegisterMeta(
        friendly_name="Compressor Runtime",
        device_class="duration",
        unit="h",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsCompressorStarts": RegisterMeta(
        friendly_name="Compressor Starts",
        icon="mdi:counter",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsFan1Hours": RegisterMeta(
        friendly_name="Fan 1 Runtime",
        device_class="duration",
        unit="h",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsFan2Hours": RegisterMeta(
        friendly_name="Fan 2 Runtime",
        device_class="duration",
        unit="h",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsBuildingCPumpStarts": RegisterMeta(
        friendly_name="Building Pump Starts",
        icon="mdi:counter",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsBuildingPumpHours": RegisterMeta(
        friendly_name="Building Pump Runtime",
        device_class="duration",
        unit="h",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.CompressorHc": RegisterMeta(
        friendly_name="Compressor HC",
        icon="mdi:information",
        entity_category="diagnostic",
        enabled=False,
    ),
    "hmu.CompressorHc.runtime": RegisterMeta(
        friendly_name="Compressor Runtime (HC)",
        device_class="duration",
        unit="min",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
        enabled=False,
    ),
    "hmu.CompressorHc.cycles": RegisterMeta(
        friendly_name="Compressor Starts (HC)",
        icon="mdi:counter",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
        enabled=False,
    ),
    "hmu.CompressorHwc": RegisterMeta(
        friendly_name="Compressor DHW",
        icon="mdi:information",
        entity_category="diagnostic",
        enabled=False,
    ),
    "hmu.CompressorHwc.runtime": RegisterMeta(
        friendly_name="Compressor Runtime (DHW)",
        device_class="duration",
        unit="min",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
        enabled=False,
    ),
    "hmu.CompressorHwc.cycles": RegisterMeta(
        friendly_name="Compressor Starts (DHW)",
        icon="mdi:counter",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
        enabled=False,
    ),
    "hmu.RunStatsCompressorHc": RegisterMeta(
        friendly_name="Compressor HC Stats",
        icon="mdi:information",
        entity_category="diagnostic",
        enabled=False,
    ),
    "hmu.RunStatsCompressorHc.runtime": RegisterMeta(
        friendly_name="Compressor Runtime (HC)",
        device_class="duration",
        unit="min",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsCompressorHc.cycles": RegisterMeta(
        friendly_name="Compressor Starts (HC)",
        icon="mdi:counter",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsCompressorHwc": RegisterMeta(
        friendly_name="Compressor DHW Stats",
        icon="mdi:information",
        entity_category="diagnostic",
        enabled=False,
    ),
    "hmu.RunStatsCompressorHwc.runtime": RegisterMeta(
        friendly_name="Compressor Runtime (DHW)",
        device_class="duration",
        unit="min",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsCompressorHwc.cycles": RegisterMeta(
        friendly_name="Compressor Starts (DHW)",
        icon="mdi:counter",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsFan1Starts": RegisterMeta(
        friendly_name="Fan 1 Starts",
        icon="mdi:counter",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsFan2Starts": RegisterMeta(
        friendly_name="Fan 2 Starts",
        icon="mdi:counter",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsHcHours": RegisterMeta(
        friendly_name="Heating Runtime",
        device_class="duration",
        unit="h",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsHMUHours": RegisterMeta(
        friendly_name="HMU Runtime",
        device_class="duration",
        unit="h",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStatsHwcHours": RegisterMeta(
        friendly_name="DHW Runtime",
        device_class="duration",
        unit="h",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStats4PortValveHours": RegisterMeta(
        friendly_name="4-Port Valve Runtime",
        device_class="duration",
        unit="h",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.RunStats4PortValveSwitches": RegisterMeta(
        friendly_name="4-Port Valve Switches",
        icon="mdi:counter",
        state_class="total_increasing",
        entity_category="diagnostic",
        entity_type="sensor",
    ),
    "hmu.PowerConsumptionHmu": RegisterMeta(
        friendly_name="Power Consumption (HMU)",
        device_class="power",
        unit="kW",
        state_class="measurement",
        enabled=False,
    ),
    "hmu.BuildingCircuitFlow": RegisterMeta(
        friendly_name="Building Circuit Flow",
        icon="mdi:water",
        unit="l/h",
        entity_type="sensor",
    ),
    "hmu.DateTime": RegisterMeta(
        friendly_name="Date/Time",
        icon="mdi:clock",
        entity_category="diagnostic",
    ),
}
